package com.wemgmemgfang.bt.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wemgmemgfang.bt.entity.UserInfo;
import com.wemgmemgfang.bt.entity.CollectionInfo;

import com.wemgmemgfang.bt.database.UserInfoDao;
import com.wemgmemgfang.bt.database.CollectionInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig collectionInfoDaoConfig;

    private final UserInfoDao userInfoDao;
    private final CollectionInfoDao collectionInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        collectionInfoDaoConfig = daoConfigMap.get(CollectionInfoDao.class).clone();
        collectionInfoDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        collectionInfoDao = new CollectionInfoDao(collectionInfoDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(CollectionInfo.class, collectionInfoDao);
    }
    
    public void clear() {
        userInfoDaoConfig.clearIdentityScope();
        collectionInfoDaoConfig.clearIdentityScope();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public CollectionInfoDao getCollectionInfoDao() {
        return collectionInfoDao;
    }

}
