package com.wemgmemgfang.bt.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wemgmemgfang.bt.entity.CollectionInfo;
import com.wemgmemgfang.bt.entity.DownVideoInfo;
import com.wemgmemgfang.bt.entity.UserInfo;

import com.wemgmemgfang.bt.database.CollectionInfoDao;
import com.wemgmemgfang.bt.database.DownVideoInfoDao;
import com.wemgmemgfang.bt.database.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionInfoDaoConfig;
    private final DaoConfig downVideoInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final CollectionInfoDao collectionInfoDao;
    private final DownVideoInfoDao downVideoInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionInfoDaoConfig = daoConfigMap.get(CollectionInfoDao.class).clone();
        collectionInfoDaoConfig.initIdentityScope(type);

        downVideoInfoDaoConfig = daoConfigMap.get(DownVideoInfoDao.class).clone();
        downVideoInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        collectionInfoDao = new CollectionInfoDao(collectionInfoDaoConfig, this);
        downVideoInfoDao = new DownVideoInfoDao(downVideoInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(CollectionInfo.class, collectionInfoDao);
        registerDao(DownVideoInfo.class, downVideoInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        collectionInfoDaoConfig.clearIdentityScope();
        downVideoInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public CollectionInfoDao getCollectionInfoDao() {
        return collectionInfoDao;
    }

    public DownVideoInfoDao getDownVideoInfoDao() {
        return downVideoInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
